import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Local fonts
const anton = localFont({
  src: "./fonts/Anton-Regular.ttf",
  variable: "--font-anton",
  weight: "400",
});

const geistMonoLocal = localFont({
  src: "./fonts/GeistMono-VariableFont_wght.ttf",
  variable: "--font-geistmono-local",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} ${geistMonoLocal.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
